- project:
    name: sandbox
    github-org: openstack-dev
    node: master
    vendor: QNAP

    jobs:
        - noop-check-communication
        - dsvm-tempest-full:
            node: devstack_slave
